CREATE SCHEMA ORDERSERVICE;

CREATE TABLE ORDERSERVICE.ORDERS (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    STATUS VARCHAR(255) NOT NULL,
    COMPLETE BOOLEAN NOT NULL,
    QUANTITY BIGINT(20) NOT NULL,
    SHIPDATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

